@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU5Yzg1Njk4LTNmNGUtNGFhNi1hY2ZkLTkwZDM3ZDUyYmQ3OCIsInVzZXJfaWQiOiJiZmI0OWUzOC0wNjAwLTQ3ZjQtOTRlYy04MzNhYzU0MDgzZjkiLCJ1c2VybmFtZSI6ImNhcm9saW5lMTIzIiwicGFzc3dvcmQiOiIkMmIkMTAkRmlkS0Nicm8xakJicUVsM0xxOWFPLmVSOU5TUm14OThkeVVaamp3TVYzcDJPWFU5TlBCaFMiLCJsYXN0X2xvZ2luIjpudWxsLCJjcmVhdGVkX2F0IjoiMjAyNS0xMC0wOFQxNzoxOTo1OC43NTlaIiwiaWF0IjoxNzYwMTI2MzQxLCJleHAiOjE3NjAxMjk5NDF9.DQQs2t9SeN6phUx2iHnu2Tl87ig5UZ8WRilbXwL9NGQ
@id = bfb49e38-0600-47f4-94ec-833ac54083f9

@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU5Yzg1Njk4LTNmNGUtNGFhNi1hY2ZkLTkwZDM3ZDUyYmQ3OCIsInVzZXJfaWQiOiJiZmI0OWUzOC0wNjAwLTQ3ZjQtOTRlYy04MzNhYzU0MDgzZjkiLCJ1c2VybmFtZSI6ImNhcm9saW5lMTIzIiwicGFzc3dvcmQiOiIkMmIkMTAkRmlkS0Nicm8xakJicUVsM0xxOWFPLmVSOU5TUm14OThkeVVaamp3TVYzcDJPWFU5TlBCaFMiLCJsYXN0X2xvZ2luIjpudWxsLCJjcmVhdGVkX2F0IjoiMjAyNS0xMC0wOFQxNzoxOTo1OC43NTlaIiwiaWF0IjoxNzU5OTQ1NDA2fQ.Jj8lN-AARmcdGUC6NvUB1VrnrgPxdPKKXwNIfyq6Hco
@id2 = 04fea3eb-9b70-4f27-9b07-6d1349913b6e

### GET all table chat
GET http://localhost:4000/chat

### GET chat by id_chat
GET http://localhost:4000/chat/835894f9-616d-4f81-b157-b7fb394d9cf7

### GET a chat if have conversations by id_chat
GET http://localhost:4000/chat/conversations/835894f9-616d-4f81-b157-b7fb394d9cf7

### POST init chat conversation with id_other_user
POST http://localhost:4000/chat/{{id2}}
Authorization: Bearer {{token}}

### DELETE a chat conversation with id_chat
DELETE http://localhost:4000/chat/delete/835894f9-616d-4f81-b157-b7fb394d9cf7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijc2MjE3OTc3LTRjZWMtNGQ3YS1hOTg2LTNjODI0YjRmODRiMiIsInVzZXJfaWQiOiI2NGNmNmUzOS05ZGNkLTQzYzAtYmMxMS00M2VmNDM4ZGE0OTciLCJ1c2VybmFtZSI6Impvc2VoZXJuYW5kZWNpdG8iLCJwYXNzd29yZCI6IiQyYiQxMCR2ang4eHpucktMZURmeld0RW1BV0guaHFlZS5zd0Iyd3hLNVhDU2NGSGcxVzNxWjFzcmJNNiIsImxhc3RfbG9naW4iOm51bGwsImNyZWF0ZWRfYXQiOiIyMDI1LTEwLTA4VDE3OjI1OjE4LjUyOFoiLCJpYXQiOjE3NjAxMjc3ODAsImV4cCI6MTc2MDEzMTM4MH0.GTeWuwwcY2Os4v_kYcZjfBQHkxfmlncqCAxX9VHf7QU

