@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU5Yzg1Njk4LTNmNGUtNGFhNi1hY2ZkLTkwZDM3ZDUyYmQ3OCIsInVzZXJfaWQiOiJiZmI0OWUzOC0wNjAwLTQ3ZjQtOTRlYy04MzNhYzU0MDgzZjkiLCJ1c2VybmFtZSI6ImNhcm9saW5lMTIzIiwicGFzc3dvcmQiOiIkMmIkMTAkRmlkS0Nicm8xakJicUVsM0xxOWFPLmVSOU5TUm14OThkeVVaamp3TVYzcDJPWFU5TlBCaFMiLCJsYXN0X2xvZ2luIjpudWxsLCJjcmVhdGVkX2F0IjoiMjAyNS0xMC0wOFQxNzoxOTo1OC43NTlaIiwiaWF0IjoxNzYwMTMxMjAyLCJleHAiOjE3NjAxMzQ4MDJ9.zYs5U2XRDHEhfO2l6JPP4Ud3U1iwgY-TCLZJySI-4wI
@id = bfb49e38-0600-47f4-94ec-833ac54083f9

@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzOWIzNmE4LTYzOWEtNDdmMy1iZTY2LWRhZGIxY2NjNzBhZCIsInVzZXJfaWQiOiIwNGZlYTNlYi05YjcwLTRmMjctOWIwNy02ZDEzNDk5MTNiNmUiLCJ1c2VybmFtZSI6Im1hcmlhZWV1IiwicGFzc3dvcmQiOiIkMmIkMTAkUC9jLm4zYXNKTi9PNWtlMjF0TU1PLm1pTHJCVk5CQzVxZ1YubnQxRHQvUWNaVWQzYUNaZ2kiLCJsYXN0X2xvZ2luIjpudWxsLCJjcmVhdGVkX2F0IjoiMjAyNS0xMC0wOFQxNzoyODowMy44MjBaIiwiaWF0IjoxNzYwMTMyODQ2LCJleHAiOjE3NjAxMzY0NDZ9.M-zFvEI1aDB-R0cntRgVKx5mfW0eZNydMve1GF5oyAI
@id2 = 04fea3eb-9b70-4f27-9b07-6d1349913b6e


### GET all table message
GET http://localhost:4000/message

### GET a message by id_message
GET http://localhost:4000/message/a5a2b347-eaf6-49ca-861d-9f113c2cc27c

### POST send message with id_chat and user_id from the one who sends the message
POST http://localhost:4000/message?chat_id=835894f9-616d-4f81-b157-b7fb394d9cf7&user_id={{id2}}
Authorization: Bearer {{token2}}
Content-Type: application/json

{
  "message": "Hola, Muy bien"
}

### PUT update message with message_id, chat_id and user_id from the one who sends the message
PUT http://localhost:4000/message?message_id=a5a2b347-eaf6-49ca-861d-9f113c2cc27c&chat_id=835894f9-616d-4f81-b157-b7fb394d9cf7&user_id={{id}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "message": "Hola, mejor escrito",
  "file_url": "image.png"
}

### DELETE a message with id_message
DELETE http://localhost:4000/message/5fa2f800-7038-4dd3-9ef0-49dcf14c1551
Authorization: Bearer {{token}}

