@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU1N2U3NmRiLTViMTktNDVhNi1hZDJjLTg5NDkzZjk0YzAxNiIsInVzZXJfaWQiOiIyZmRmZWJmZS1mOWE3LTRiOWYtYmE0Yi1iN2VhZGJiYTNmMzQiLCJ1c2VybmFtZSI6ImNhcmxpdG8xMjMiLCJwYXNzd29yZCI6IiQyYiQxMCRFVmJYNzlkT0VuZ2RoTmFlM05uSU9PNVVFc0lMVmdZQ2c5TEJPLm5DVnFmaVFINm9SbTF3cSIsImxhc3RfbG9naW4iOm51bGwsImNyZWF0ZWRfYXQiOiIyMDI1LTEwLTA4VDE3OjMxOjAzLjQ0NFoiLCJpYXQiOjE3NTk5NDQ3NjN9.VScmvc7RXflLAq1APqqYNnoAeJwlJnk0GXSABuQKL8E
@id = 2fdfebfe-f9a7-4b9f-ba4b-b7eadbba3f34

@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU5Yzg1Njk4LTNmNGUtNGFhNi1hY2ZkLTkwZDM3ZDUyYmQ3OCIsInVzZXJfaWQiOiJiZmI0OWUzOC0wNjAwLTQ3ZjQtOTRlYy04MzNhYzU0MDgzZjkiLCJ1c2VybmFtZSI6ImNhcm9saW5lMTIzIiwicGFzc3dvcmQiOiIkMmIkMTAkRmlkS0Nicm8xakJicUVsM0xxOWFPLmVSOU5TUm14OThkeVVaamp3TVYzcDJPWFU5TlBCaFMiLCJsYXN0X2xvZ2luIjpudWxsLCJjcmVhdGVkX2F0IjoiMjAyNS0xMC0wOFQxNzoxOTo1OC43NTlaIiwiaWF0IjoxNzU5OTQ1NDA2fQ.Jj8lN-AARmcdGUC6NvUB1VrnrgPxdPKKXwNIfyq6Hco
@id2 = bfb49e38-0600-47f4-94ec-833ac54083f9

### POST like to a post
POST http://localhost:4000/like/
Authorization: Bearer {{token2}}
Content-Type: application/json

{
  "like_from": "bfb49e38-0600-47f4-94ec-833ac54083f9",
  "like_to_post": "2cd89be1-0bbf-4d02-b921-55eaec2e5ca4"
}

### GET table like
GET http://localhost:4000/like/

### GET like by user_id
GET http://localhost:4000/like/{{id}}

### DELETE like by post_id
DELETE http://localhost:4000/like/2cd89be1-0bbf-4d02-b921-55eaec2e5ca4
Authorization: Bearer {{token}}
