@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU5Yzg1Njk4LTNmNGUtNGFhNi1hY2ZkLTkwZDM3ZDUyYmQ3OCIsInVzZXJfaWQiOiJiZmI0OWUzOC0wNjAwLTQ3ZjQtOTRlYy04MzNhYzU0MDgzZjkiLCJ1c2VybmFtZSI6ImNhcm9saW5lMTIzIiwicGFzc3dvcmQiOiIkMmIkMTAkRmlkS0Nicm8xakJicUVsM0xxOWFPLmVSOU5TUm14OThkeVVaamp3TVYzcDJPWFU5TlBCaFMiLCJsYXN0X2xvZ2luIjpudWxsLCJjcmVhdGVkX2F0IjoiMjAyNS0xMC0wOFQxNzoxOTo1OC43NTlaIiwiaWF0IjoxNzYwMTI1MjI5LCJleHAiOjE3NjAxMjg4Mjl9.AnzjKS4g01AWheJR8PGUS4plmQRyCT5MGZtQJOdEViM
@id = bfb49e38-0600-47f4-94ec-833ac54083f9

@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU5Yzg1Njk4LTNmNGUtNGFhNi1hY2ZkLTkwZDM3ZDUyYmQ3OCIsInVzZXJfaWQiOiJiZmI0OWUzOC0wNjAwLTQ3ZjQtOTRlYy04MzNhYzU0MDgzZjkiLCJ1c2VybmFtZSI6ImNhcm9saW5lMTIzIiwicGFzc3dvcmQiOiIkMmIkMTAkRmlkS0Nicm8xakJicUVsM0xxOWFPLmVSOU5TUm14OThkeVVaamp3TVYzcDJPWFU5TlBCaFMiLCJsYXN0X2xvZ2luIjpudWxsLCJjcmVhdGVkX2F0IjoiMjAyNS0xMC0wOFQxNzoxOTo1OC43NTlaIiwiaWF0IjoxNzU5OTQ1NDA2fQ.Jj8lN-AARmcdGUC6NvUB1VrnrgPxdPKKXwNIfyq6Hco
@id2 = 64cf6e39-9dcd-43c0-bc11-43ef438da497

### POST follow other user with id_other_user
POST http://localhost:4000/follow/c62ecefe-5c92-4b04-8d33-fa382252380e
Authorization: Bearer {{token}}

### GET list table follow
GET http://localhost:4000/follow

### GET following (siguiendo)
GET http://localhost:4000/follow/following/{{id}}

### GET followers (seguidores)
GET http://localhost:4000/follow/followers/{{id}}

### DELETE unfollow other user with id_other_user
DELETE http://localhost:4000/follow/unfollowed/c62ecefe-5c92-4b04-8d33-fa382252380e
Authorization: Bearer {{token}}

